//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#pragma once

Gpio GENERATED_OUTPUTS[] = {
	Gpio::B8, // INJ14 (PB8)
	Gpio::B9, // INJ23 (PB9)
	Gpio::A8, // IGN (PA8)
	Gpio::B10, // Fuel Pump (PB10)
	Gpio::D12, // AC Clutch (PD12)
	Gpio::B0, // IACV (PB0)
	Gpio::D13, // MIL (PD13)
// "INJ14 (PB8)",
// "INJ23 (PB9)",
// "IGN (PA8)",
// "Fuel Pump (PB10)",
// "AC Clutch (PD12)",
// "IACV (PB0)",
// "MIL (PD13)",
}
