//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/Board_GDI.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/black23 .yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/black35 .yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/white35 .yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::A0: return "Analog Voltage 5(fuel high pressure)";
		case Gpio::A1: return "Analog Voltage 6(Oil pressure)";
		case Gpio::A2: return "Analog Voltage 7";
		case Gpio::A3: return "Analog Voltage 8(MAP)";
		case Gpio::A4: return "Analog Voltage 9";
		case Gpio::A5: return "Analog Voltage 10";
		case Gpio::A6: return "Analog Voltage 11";
		case Gpio::A8: return "Highside 2";
		case Gpio::A9: return "Highside 1";
		case Gpio::B0: return "Analog Thermistor 3";
		case Gpio::B1: return "Analog Temp 4(Fuel levl)";
		case Gpio::B4: return "ingect 8";
		case Gpio::B5: return "Pump HW start 5";
		case Gpio::B6: return "Pump HW start 6";
		case Gpio::B7: return "pump 1 low";
		case Gpio::B8: return "pump 2 low";
		case Gpio::B9: return "Lowside 13";
		case Gpio::C0: return "Analog Volt 1(PPS2)";
		case Gpio::C1: return "Analog Volt 2(PPS1)";
		case Gpio::C2: return "Analog Voltage 3(TPS2)";
		case Gpio::C3: return "Analog Voltage 4(TPS1)";
		case Gpio::C4: return "Analog Thermistor 1(CLT)";
		case Gpio::C5: return "Analog Thermistor 2(IAT)";
		case Gpio::C6: return "Digital 1";
		case Gpio::C7: return "Ign 5";
		case Gpio::C8: return "Ign 4";
		case Gpio::C9: return "Ign 3";
		case Gpio::D10: return "STM32 PD10";
		case Gpio::D11: return "STM32 PD11";
		case Gpio::D12: return "STM32 PD12";
		case Gpio::D13: return "STM32 PD13";
		case Gpio::D14: return "Highside 4";
		case Gpio::D15: return "Highside 3";
		case Gpio::D3: return "Ign 2";
		case Gpio::D4: return "Ign 1";
		case Gpio::D7: return "ingect H 1";
		case Gpio::D8: return "STM32 PD8";
		case Gpio::D9: return "STM32 PD9";
		case Gpio::E0: return "Lowside 14";
		case Gpio::E1: return "Lowside 15";
		case Gpio::E11: return "Digital 2";
		case Gpio::E12: return "Digital 3";
		case Gpio::E13: return "Digital 5(Start button)";
		case Gpio::E14: return "Digital 4";
		case Gpio::E15: return "Digital 6";
		case Gpio::E2: return "Lowside 16";
		case Gpio::F6: return "EGT CS";
		case Gpio::G10: return "ingect H 3";
		case Gpio::G11: return "ingect H 4";
		case Gpio::G12: return "ingect 5";
		case Gpio::G13: return "ingect 6";
		case Gpio::G14: return "ingect 7";
		case Gpio::G5: return "Starter";
		case Gpio::G6: return "Ign 8";
		case Gpio::G7: return "Ign 7";
		case Gpio::G8: return "Ign 6";
		case Gpio::G9: return "ingect H 2";
		default: return nullptr;
	}
	return nullptr;
}
