//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/Board_GDI.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/black23 .yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/black35 .yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/white35 .yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::D7, // ingect H 1
	Gpio::G9, // ingect H 2
	Gpio::G10, // ingect H 3
	Gpio::G11, // ingect H 4
	Gpio::B5, // Pump HW start 5
	Gpio::B6, // Pump HW start 6
	Gpio::E0, // Lowside 14
	Gpio::E1, // Lowside 15
	Gpio::B9, // Lowside 13
	Gpio::E2, // Lowside 16
	Gpio::G12, // ingect 5
	Gpio::G13, // ingect 6
	Gpio::G14, // ingect 7
	Gpio::B4, // ingect 8
	Gpio::A8, // Highside 2
	Gpio::G5, // Starter
	Gpio::D15, // Highside 3
	Gpio::B8, // pump 2 low
	Gpio::B7, // pump 1 low
	Gpio::D8, // STM32 PD8
	Gpio::D9, // STM32 PD9
	Gpio::D10, // STM32 PD10
	Gpio::D11, // STM32 PD11
	Gpio::D12, // STM32 PD12
	Gpio::D13, // STM32 PD13
	Gpio::A9, // Highside 1
	Gpio::D14, // Highside 4
	Gpio::C7, // Ign 5
	Gpio::G7, // Ign 7
	Gpio::G6, // Ign 8
	Gpio::D4, // Ign 1
	Gpio::D3, // Ign 2
	Gpio::C9, // Ign 3
	Gpio::C8, // Ign 4
	Gpio::G8, // Ign 6
	Gpio::F6, // EGT CS
// "ingect H 1",
// "ingect H 2",
// "ingect H 3",
// "ingect H 4",
// "Pump HW start 5",
// "Pump HW start 6",
// "Lowside 14",
// "Lowside 15",
// "Lowside 13",
// "Lowside 16",
// "ingect 5",
// "ingect 6",
// "ingect 7",
// "ingect 8",
// "Highside 2",
// "Starter",
// "Highside 3",
// "pump 2 low",
// "pump 1 low",
// "STM32 PD8",
// "STM32 PD9",
// "STM32 PD10",
// "STM32 PD11",
// "STM32 PD12",
// "STM32 PD13",
// "Highside 1",
// "Highside 4",
// "Ign 5",
// "Ign 7",
// "Ign 8",
// "Ign 1",
// "Ign 2",
// "Ign 3",
// "Ign 4",
// "Ign 6",
// "EGT CS",
}
